import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useMutation } from 'convex/react';
import { api } from '../../convex/_generated/api';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';

export const Login: React.FC = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const navigate = useNavigate();

    // @ts-ignore - The API will be generated by Convex
    const loginMutation = useMutation(api.auth?.login || api.auth.login);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError('');
        setIsLoading(true);

        try {
            const token = await loginMutation({ email, password });
            if (token) {
                // Store the session token 
                localStorage.setItem('admin_token', token);
                navigate('/dashboard');
            } else {
                setError('Invalid credentials.');
            }
        } catch (err) {
            setError('An error occurred during authentication.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#1F1E1E] text-[#E0E0E0] font-[Inter,sans-serif] flex flex-col font-sans">
            <Header onAboutClick={() => navigate('/')} onNavClick={() => navigate('/')} />

            <main className="flex-1 flex flex-col justify-center items-center p-6 pt-24 pb-12">
                <div className="w-full max-w-[440px] animate-in fade-in slide-in-from-bottom-4 duration-500">

                    {/* Convex Logo Placeholder / Sign in text */}
                    <div className="text-center mb-8 flex flex-col items-center">
                        {/* Placeholder for Convex-like logo */}
                        <div className="w-12 h-12 mb-6 rounded-full bg-gradient-to-tr from-[#FF5C33] via-[#E82A6A] to-[#8C1B74] flex items-center justify-center p-1">
                            <div className="w-full h-full bg-[#1F1E1E] rounded-full overflow-hidden relative">
                                <div className="absolute inset-0 bg-gradient-to-tr from-[#FF5C33] via-[#E82A6A] to-[#8C1B74] opacity-80" style={{ clipPath: 'polygon(0 0, 100% 0, 100% 50%, 0 50%)' }}></div>
                            </div>
                        </div>
                        <h1 className="text-2xl font-bold tracking-tight text-white m-0">Sign in to Gnanie</h1>
                    </div>

                    <div className="bg-[#2D2A26] rounded-xl p-8 border border-white/5 shadow-2xl">

                        <form onSubmit={handleSubmit} className="space-y-6">
                            {error && (
                                <div className="p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-500 text-sm font-medium text-center">
                                    {error}
                                </div>
                            )}

                            <div className="space-y-2">
                                <label className="text-sm font-bold text-white tracking-wide block">Email</label>
                                <input
                                    type="email"
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                    className="w-full h-[46px] bg-[#1E1C1A] border border-[#3E3A36] rounded text-white px-4 focus:outline-none focus:border-[#7A7570] transition-colors placeholder-[#888]"
                                    placeholder="Your email address"
                                    required
                                />
                            </div>

                            {/* Added password field for the admin auth, styled to match */}
                            <div className="space-y-2">
                                <label className="text-sm font-bold text-white tracking-wide block">Password</label>
                                <input
                                    type="password"
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    className="w-full h-[46px] bg-[#1E1C1A] border border-[#3E3A36] rounded text-white px-4 focus:outline-none focus:border-[#7A7570] transition-colors placeholder-[#888]"
                                    placeholder="Your password"
                                    required
                                />
                            </div>

                            <button
                                type="submit"
                                disabled={isLoading}
                                className="w-full h-[46px] bg-[#33302C] hover:bg-[#3E3A36] border border-[#444] text-white rounded font-bold text-[15px] transition-colors flex items-center justify-center disabled:opacity-50 mt-2"
                            >
                                {isLoading ? (
                                    <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                    </svg>
                                ) : (
                                    'Continue with SSO'
                                )}
                            </button>
                        </form>
                    </div>
                </div>
            </main>

            <Footer onNavClick={() => navigate('/')} />
        </div>
    );
};
